version: 2.1

orbs:
  docker: circleci/docker@1.5.0

jobs:
  build:
    docker:
      - image: perl:5.30-slim
    steps:
      - checkout
      - run: apt-get update && apt-get install -y build-essential libssl-dev carton
      - run: carton install
      - run: find /root/.cpanm/work/ -name build.log -exec cat {} \;
      - run: carton exec -- prove t

workflows:
  main:
    jobs:
      - build
      # - perl/test-linux:
      #     matrix:
      #       parameters:
      #         perl-version:
      #           - '5.24'
      #           - '5.26'
      #           - '5.28'
      #           - '5.30'
      #     requires:
      #       - build
      # - docker/publish:
      #     requires:
      #       - perl/test-linux
      #     deploy: false
      #     image: darksoy/$CIRCLE_PROJECT_REPONAME
