version: 2.1

orbs:
  docker: circleci/docker@1.5.0

jobs:
  build:
    environment:
      PERL_CPANM_OPT: "--cascade-search --save-dists=/root/.cpanm/cache --mirror=/root/.cpanm/cache --mirror=https://search.cpan.org/CPAN"
    docker:
      - image: perl:5.30
    steps:
      - checkout
      - restore_cache:
          key: cpan-v3-{{ .Branch }}-{{ checksum "cpanfile.snapshot" }}
          paths:
              - /root/.cpanm
      - run: cpanm --notest Carton
      - run: carton install --deployment
      - run: carton exec -- prove t
      - run: ls /root/.cpanm
      - run: rm -rf local/
      - persist_to_workspace:
          root: .
          paths:
            - "*"
      - save_cache:
          key: cpan-v3-{{ .Branch }}-{{ checksum "cpanfile.snapshot" }}
          paths:
              - /root/.cpanm
  test:
    environment:
      PERL_CPANM_OPT: "--cascade-search --save-dists=/root/.cpanm/cache --mirror=/root/.cpanm/cache --mirror=https://search.cpan.org/CPAN"
    parameters:
      version:
        type: string
    docker:
      - image: perl:<< parameters.version >>
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          key: cpan-v3-{{ .Branch }}-{{ checksum "cpanfile.snapshot" }}
          paths:
              - /root/.cpanm
      - run: cpanm --notest Carton
      - run: carton install --deployment
      - run: carton exec -- perl -V | head
      - run: carton exec -- prove t

workflows:
  main:
    jobs:
      - build
      - docker/publish:
          context:
            - docker-hub-credentials
          requires:
            - build
          deploy: false
          image: darksoy/$CIRCLE_PROJECT_REPONAME
          extra_build_args: "--target prod"
