version: 2.1

orbs:
  perl: circleci/perl@1.0.0
  docker: circleci/docker@1.5.0

workflows:
  main:
    jobs:
      - perl/build:
          codecov: true
      - perl/test-linux:
          matrix:
            parameters:
              perl-version:
                - '5.24'
                - '5.26'
                - '5.28'
                - '5.30'
          requires:
            - perl/build
      - docker/publish:
          requires:
            - build-and-publish
          deploy: false
          image: darksoy/$CIRCLE_PROJECT_REPONAME
