version: 2.1

orbs:
  docker: circleci/docker@1.5.0

jobs:
  build:
    docker:
      - image: perl:5.30
    steps:
      - checkout
      - run: cpanm --notest Carton
      - run: carton install
      - run: carton exec -- prove t
      - run: ls
      - persist_to_workspace:
          root: /root
          path: project
  test:
    parameters:
      version:
        type: string
    docker:
      - image: perl:<< parameters.version >>
    steps:
      - attach_workspace:
          at: .
      - run: carton exec -- perl -V | head
      - run: carton exec -- prove t

workflows:
  main:
    jobs:
      - build
      - test:
          matrix:
            parameters:
              version:
                - '5.24'
                - '5.26'
                - '5.28'
                - '5.30'
          requires:
            - build
      # - docker/publish:
      #     requires:
      #       - perl/test-linux
      #     deploy: false
      #     image: darksoy/$CIRCLE_PROJECT_REPONAME
