version: 2.1

orbs:
  perl: circleci/perl@1.0.0
  docker: circleci/docker@1.5.0

jobs:
  prep:
    docker:
      - image: cimg/base
    steps:
      - checkout
      - run: echo $PWD
      - run: mkdir build_dir

workflows:
  main:
    jobs:
      - prep
      - perl/build:
          codecov: false
      - perl/test-linux:
          matrix:
            parameters:
              perl-version:
                - '5.24'
                - '5.26'
                - '5.28'
                - '5.30'
          requires:
            - perl/build
      - docker/publish:
          requires:
            - perl/test-linux
          deploy: false
          image: darksoy/$CIRCLE_PROJECT_REPONAME
